version: "3"

services:
  db:
    image: mysql:5
    container_name: music_db
    env_file: .env
    volumes:
      - data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: music_web
    volumes:
      - upload:/root/upload/images
    restart: always

  frpc-inter:
    image: snowdreamtech/frpc
    container_name: music_frpc_inter
    volumes:
      - "./frpc/frpc1.ini:/etc/frp/frpc.ini"
    restart: always

  frpc-out:
    image: snowdreamtech/frpc
    container_name: music_frpc_out
    volumes:
      - "./frpc/frpc2.ini:/etc/frp/frpc.ini"
    restart: always

volumes:
  data:
  upload:
